Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Specify the operating system image for the virtual machine
  config.vm.synced_folder "../", "/project" # Sync the project folder from the host to the guest VM

  config.vm.define "control" do |ctrl| # Define and configure the specific VM named control
    ctrl.vm.hostname = "control" # Set the hostname used inside the guest OS
    ctrl.vm.network "private_network", ip: "192.168.99.10" # Assign a static IP to enable inter-node communication

    ctrl.vm.provider "virtualbox" do |vb| # Set hardware limits for the VirtualBox hypervisor
      vb.memory = "2048" # Allocate 2GB of RAM
      vb.cpus = 2 # Allocate 2 CPU cores
      vb.name = "iac-learning-node" # Set the display name in the VirtualBox application
    end

    ctrl.vm.provision "shell", inline: "apt-get update -y" # Check for available updates (always do before installing/upgrading). "apt-get upgrade installs the updates found"

    ctrl.vm.provision "ansible_local" do |ansible| # Use Ansible installed on the VM to run configuration tasks
      ansible.install = true # Automatically install Ansible on the guest if it is not present
      ansible.inventory_path = "/project/inventory.ini" # Define the path to the Ansible inventory file
      ansible.playbook = "/project/site.yaml" # Define the path to the main Ansible playbook
    end
  end
end