Vagrant.configure("2") do |config|
  # Define OS image
  config.vm.box = "ubuntu/jammy64"

  # Assign a private, static IP address.
  config.vm.network "private_network", ip: "192.168.99.10"

  # Define VM provider and hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "iac-learning-node"
  end
end